version: '3.8'

services:
  db:
    image: postgres:15
    container_name: talenthub-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passwaordb
      POSTGRES_DB: namedb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
